### ISSUE TITLE
Missing features from Fooocus

### ISSUE THREAD

**Issue by VelocityRa** [runew0lf/RuinedFooocus#128]
Is this fork maintained regarding rebases? I see it's currently 623 commits behind.

The readme outlines what this has over Fooocus, but not what's missing.

**Comment by yownas** [comment]
No. The original Fooocus project decided to take another direction than we wanted to take. So I would rather see it as 645 commits ahead, in the direction we wanted.

Ruined Fooocus is "missing" a lot of features. But that is intentional. Instead of trying to be the next a1111 that does everything, we aim to fill the niche of being easy to use without a steep learning curve but still have enough features to experiment and get a feel for what you can do.

...and when people need something more advanced there is ComfyUI or a1111/SD.Next.

**Comment by VelocityRa** [comment]
Fair enough, regarding features. Was mainly thinking of optimizations, updating deps, maintenance. Whether such commits are rebased/cherry-picked on a case by case basis.

**Comment by runew0lf** [comment]
Oh thats easy, we stripped out a lot of the crap from fooocus, rewrote a lot of the backend to make more sense, and stopped implementing any changes before V2 had dropped and like we said, we went our own way, the easiest way to see whats different is.. to try it!

**Comment by VelocityRa** [comment]
I see :) Sounds good, thanks for the prompt replies.
I can close this now.
